### ISSUE TITLE
Can you provide more context around what this does?

### ISSUE THREAD

**Issue by jcokc** [motschel123/Mac-Contact-Sync-Obsidian#2]
1. Can you define what it means to "sync contacts" to Obsidian? 
2. What do you do with this after you initiate the sync?
3. What is the use case for this?

**Comment by motschel123** [comment]
1. Taking the information stored inside the Contacts app and making them accessible in Obsidian by creating/updating files in your obsidian vault.
2. Anything you would do with normal Notes your write down in Obsidian.
3. Like Obsidian as a whole, there is no one special use case. You can do whatever suits you 

I hope this clarification helps you. As there is no proposed issues I will close this thread.
