### ISSUE TITLE
message error

### ISSUE THREAD

**Issue by jojoB31** [motschel123/Mac-Contact-Sync-Obsidian#8]
Hello, I try the plugin but i have an error message : 

Error retrieving contacts:
execution error: Error: Error: Délai dépassé pour un AppleEvent. (-1712)

Do you know where that can come from?
thank you

**Comment by motschel123** [comment]
It seems like there is some problem with the contacts app or Apple internal logic.
Could you try to open the contacts app before running the obsidian plugin command.
Or try to reduce the amount of contacts in your smart list.

**Comment by jojoB31** [comment]
Yes, thanks.
If i first open contact, it doesn't work
If I select 128 contact that work perfectly !!
(326 contacts don't work) 
Thanks so much

**Comment by motschel123** [comment]
Glad I could help.
I already spent a lot of time improving/increasing the contact retrieval, so unless there is a big demand, don't expect further increases.
